-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Evander.Object exposing (..)


type PageInfo
    = PageInfo


type Payment
    = Payment


type PaymentConnection
    = PaymentConnection


type PaymentEdge
    = PaymentEdge
