-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Evander.ScalarCodecs exposing (..)

import Evander.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Evander.Scalar.Id


codecs : Evander.Scalar.Codecs Id
codecs =
    Evander.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
