-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Evander.Object.Payment exposing (..)

import Evander.InputObject
import Evander.Interface
import Evander.Object
import Evander.Scalar
import Evander.ScalarCodecs
import Evander.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Evander.ScalarCodecs.Id Evander.Object.Payment
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Evander.ScalarCodecs.codecs |> Evander.Scalar.unwrapCodecs |> .codecId |> .decoder)


orderId : SelectionSet Evander.ScalarCodecs.Id Evander.Object.Payment
orderId =
    Object.selectionForField "ScalarCodecs.Id" "orderId" [] (Evander.ScalarCodecs.codecs |> Evander.Scalar.unwrapCodecs |> .codecId |> .decoder)


status : SelectionSet String Evander.Object.Payment
status =
    Object.selectionForField "String" "status" [] Decode.string
