-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Melissa.Object.Order exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Melissa.InputObject
import Melissa.Interface
import Melissa.Object
import Melissa.Scalar
import Melissa.ScalarCodecs
import Melissa.Union


id : SelectionSet Melissa.ScalarCodecs.Id Melissa.Object.Order
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Melissa.ScalarCodecs.codecs |> Melissa.Scalar.unwrapCodecs |> .codecId |> .decoder)


productId : SelectionSet Melissa.ScalarCodecs.Id Melissa.Object.Order
productId =
    Object.selectionForField "ScalarCodecs.Id" "productId" [] (Melissa.ScalarCodecs.codecs |> Melissa.Scalar.unwrapCodecs |> .codecId |> .decoder)


quantity : SelectionSet String Melissa.Object.Order
quantity =
    Object.selectionForField "String" "quantity" [] Decode.string


status : SelectionSet String Melissa.Object.Order
status =
    Object.selectionForField "String" "status" [] Decode.string
