-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Melissa.Interface exposing (..)


type Connection
    = Connection


type Edge
    = Edge


type Node
    = Node
