-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Melissa.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Melissa.InputObject
import Melissa.Interface
import Melissa.Object
import Melissa.Scalar
import Melissa.ScalarCodecs
import Melissa.Union


type alias CreateOrderRequiredArguments =
    { order : Melissa.InputObject.CreateOrder }


createOrder :
    CreateOrderRequiredArguments
    -> SelectionSet decodesTo Melissa.Object.Order
    -> SelectionSet decodesTo RootMutation
createOrder requiredArgs____ object____ =
    Object.selectionForCompositeField "createOrder" [ Argument.required "order" requiredArgs____.order Melissa.InputObject.encodeCreateOrder ] object____ Basics.identity
