-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Melissa.Object exposing (..)


type Order
    = Order


type OrderConnection
    = OrderConnection


type OrderEdge
    = OrderEdge


type PageInfo
    = PageInfo
