-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Artemis.Object.PageInfo exposing (..)

import Artemis.InputObject
import Artemis.Interface
import Artemis.Object
import Artemis.Scalar
import Artemis.ScalarCodecs
import Artemis.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


startCursor : SelectionSet (Maybe Artemis.ScalarCodecs.Id) Artemis.Object.PageInfo
startCursor =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "startCursor" [] (Artemis.ScalarCodecs.codecs |> Artemis.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


endCursor : SelectionSet (Maybe Artemis.ScalarCodecs.Id) Artemis.Object.PageInfo
endCursor =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "endCursor" [] (Artemis.ScalarCodecs.codecs |> Artemis.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)
