-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Artemis.Object.ProductConnection exposing (..)

import Artemis.InputObject
import Artemis.Interface
import Artemis.Object
import Artemis.Scalar
import Artemis.ScalarCodecs
import Artemis.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


edges :
    SelectionSet decodesTo Artemis.Object.ProductEdge
    -> SelectionSet (List decodesTo) Artemis.Object.ProductConnection
edges object____ =
    Object.selectionForCompositeField "edges" [] object____ (Basics.identity >> Decode.list)


pageInfo :
    SelectionSet decodesTo Artemis.Object.PageInfo
    -> SelectionSet decodesTo Artemis.Object.ProductConnection
pageInfo object____ =
    Object.selectionForCompositeField "pageInfo" [] object____ Basics.identity
