-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Artemis.Object.ProductEdge exposing (..)

import Artemis.InputObject
import Artemis.Interface
import Artemis.Object
import Artemis.Scalar
import Artemis.ScalarCodecs
import Artemis.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


node :
    SelectionSet decodesTo Artemis.Object.Product
    -> SelectionSet decodesTo Artemis.Object.ProductEdge
node object____ =
    Object.selectionForCompositeField "node" [] object____ Basics.identity


cursor : SelectionSet Artemis.ScalarCodecs.Id Artemis.Object.ProductEdge
cursor =
    Object.selectionForField "ScalarCodecs.Id" "cursor" [] (Artemis.ScalarCodecs.codecs |> Artemis.Scalar.unwrapCodecs |> .codecId |> .decoder)
