-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Artemis.Object.Product exposing (..)

import Artemis.InputObject
import Artemis.Interface
import Artemis.Object
import Artemis.Scalar
import Artemis.ScalarCodecs
import Artemis.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Artemis.ScalarCodecs.Id Artemis.Object.Product
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Artemis.ScalarCodecs.codecs |> Artemis.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String Artemis.Object.Product
name =
    Object.selectionForField "String" "name" [] Decode.string


quantity : SelectionSet String Artemis.Object.Product
quantity =
    Object.selectionForField "String" "quantity" [] Decode.string


quantityUnit : SelectionSet String Artemis.Object.Product
quantityUnit =
    Object.selectionForField "String" "quantityUnit" [] Decode.string
