-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Artemis.ScalarCodecs exposing (..)

import Artemis.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Artemis.Scalar.Id


codecs : Artemis.Scalar.Codecs Id
codecs =
    Artemis.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
